In [3]:
# 1.importing libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [4]:
# 2.creating dataset
data ={
    "Roll_No": list(range(101, 131)),

    "Name": [
        "Rahul", "Priya", "Arjun", "Sneha", "Kiran",
        "Anjali", "Vikram", "Pooja", "Rohit", "Divya",
        "Aditya", "Keerthi", "Sai", "Harsha", "Nikhil",
        "Sanjana", "Varun", "Meghana", "Akash", "Swathi",
        "Manoj", "Lavanya", "Karthik", "Deepa", "Surya",
        "Neha", "Abhishek", "Teja", "Rakesh", "Bhavana"
    ],

    "CGPA": [
        8.7, 7.2, 9.1, 6.8, 8.4,
        7.5, 9.3, 6.9, 8.1, 7.8,
        9.0, 7.1, 8.8, 6.5, 8.6,
        7.7, 9.2, 7.0, 8.3, 6.7,
        8.9, 7.4, 9.4, 6.9, 8.2,
        7.6, 9.1, 7.3, 8.5, 6.6
    ],

    "Skills": [
        8, 5, 9, 3, 7,
        6, 9, 4, 7, 6,
        8, 5, 8, 3, 7,
        6, 9, 4, 7, 3,
        8, 5, 9, 4, 7,
        6, 8, 5, 1, 3
    ],

    "Projects": [
        3, 1, 4, 0, 3,
        2, 4, 1, 2, 2,
        3, 1, 3, 0, 3,
        2, 4, 1, 2, 1,
        3, 2, 4, 1, 3,
        2, 3, 1, 0, 0
    ],

    "Internships": [
        1, 0, 2, 0, 1,
        1, 2, 0, 1, 0,
        1, 0, 1, 0, 1,
        1, 2, 0, 1, 0,
        1, 1, 2, 0, 1,
        1, 1, 0, 0, 0
    ],

    "Certifications": [
        4, 2, 5, 1, 3,
        2, 5, 1, 3, 2,
        4, 2, 4, 1, 3,
        3, 5, 1, 3, 1,
        4, 2, 5, 1, 3,
        2, 4, 2, 0, 1
    ],

    "DSA_Score": [
        82, 61, 91, 48, 76,
        68, 94, 52, 74, 65,
        86, 59, 81, 45, 78,
        70, 92, 50, 73, 55,
        84, 63, 95, 49, 77,
        69, 88, 60, 22, 47
    ],

    "Placed": [
        1, 0, 1, 0, 1,
        0, 1, 0, 1, 0,
        1, 0, 1, 0, 1,
        0, 1, 0, 1, 0,
        1, 0, 1, 0, 1,
        0, 1, 0, 0, 0
    ]
}

In [5]:
# 3.craeting a dataframe
df=pd.DataFrame(data)

In [6]:
df

,Roll_No,Name,CGPA,Skills,Projects,Internships,Certifications,DSA_Score,Placed
0,101,Rahul,8.7,8,3,1,4,82,1
1,102,Priya,7.2,5,1,0,2,61,0
2,103,Arjun,9.1,9,4,2,5,91,1
3,104,Sneha,6.8,3,0,0,1,48,0
4,105,Kiran,8.4,7,3,1,3,76,1
5,106,Anjali,7.5,6,2,1,2,68,0
6,107,Vikram,9.3,9,4,2,5,94,1
7,108,Pooja,6.9,4,1,0,1,52,0
8,109,Rohit,8.1,7,2,1,3,74,1
9,110,Divya,7.8,6,2,0,2,65,0
10,111,Aditya,9.0,8,3,1,4,86,1
11,112,Keerthi,7.1,5,1,0,2,59,0
12,113,Sai,8.8,8,3,1,4,81,1
13,114,Harsha,6.5,3,0,0,1,45,0
14,115,Nikhil,8.6,7,3,1,3,78,1
15,116,Sanjana,7.7,6,2,1,3,70,0
16,117,Varun,9.2,9,4,2,5,92,1
17,118,Meghana,7.0,4,1,0,1,50,0
18,119,Akash,8.3,7,2,1,3,73,1
19,120,Swathi,6.7,3,1,0,1,55,0
20,121,Manoj,8.9,8,3,1,4,84,1
21,122,Lavanya,7.4,5,2,1,2,63,0
22,123,Karthik,9.4,9,4,2,5,95,1
23,124,Deepa,6.9,4,1,0,1,49,0
24,125,Surya,8.2,7,3,1,3,77,1
25,126,Neha,7.6,6,2,1,2,69,0
26,127,Abhishek,9.1,8,3,1,4,88,1
27,128,Teja,7.3,5,1,0,2,60,0
28,129,Rakesh,8.5,1,0,0,0,22,0
29,130,Bhavana,6.6,3,0,0,1,47,0

In [7]:
# 4. Select the features (X)

# Roll number and Name are NOT used for prediction

X = df[
    [
        "CGPA",
        "Skills",
        "Projects",
        "Internships",
        "Certifications",
        "DSA_Score"
    ]
]

In [8]:
# 4. Select the target / label (y)

# 1 = Placed
# 0 = Not Placed

y = df["Placed"]

In [9]:
y

0     1
1     0
2     1
3     0
4     1
5     0
6     1
7     0
8     1
9     0
10    1
11    0
12    1
13    0
14    1
15    0
16    1
17    0
18    1
19    0
20    1
21    0
22    1
23    0
24    1
25    0
26    1
27    0
28    0
29    0
Name: Placed, dtype: int64

In [10]:
# 6.splitting the data into train and test data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [11]:
print("Training students:", len(X_train))
print("Testing students:", len(X_test))

Training students: 24
Testing students: 6

In [12]:
# 7. Create the Machine Learning model

model = DecisionTreeClassifier(random_state=42)

In [13]:
# 8. Train the model

model.fit(X_train, y_train)

print("\nModel training completed!")

Model training completed!

In [14]:
# 9.test the model
predictions = model.predict(X_test)

print("\nActual values:   ", list(y_test))
print("Predicted values:", list(predictions))

Actual values:    [0, 0, 0, 0, 1, 0]
Predicted values: [np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(1), np.int64(0)]

In [15]:
#10 testing accuracy
accuracy = accuracy_score(y_test, predictions)

In [16]:
accuracy

0.8333333333333334

In [17]:
#11 creating a new data
#Create a completely new student

new_student = pd.DataFrame([{
    "CGPA": 8.5,
    "Skills": 0,
    "Projects": 0,
    "Internships": 0,
    "Certifications": 0,
    "DSA_Score": 22
}])

In [18]:
new_student

   CGPA  Skills  Projects  Internships  Certifications  DSA_Score
0   8.5       0         0            0               0         22

In [19]:
#12 predicting new student output
prediction = model.predict(new_student)

In [20]:
prediction

array([0])

In [21]:
# 13. Display the prediction

if prediction[0] == 1:
    print("\nPrediction: PLACED ✅")
else:
    print("\nPrediction: NOT PLACED ❌")

Prediction: NOT PLACED ❌